(function(g){var window=this;var TCa=function(a,b){return g.Ub(a,b)},i6=function(a){g.Qm(a,"zx",g.xb());
return a},j6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Tm(a.o,b,c)},UCa=function(a,b){var c=[];
g.Fk(b,function(a){try{var b=g.pD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.oD(b)&&c.push(a):c.push(a)},a);
return c},VCa=function(a,b){var c=UCa(a,b);
(0,g.D)(c,function(a){g.pD.prototype.remove.call(this,a)},a)},WCa=function(a){if(a.Jd){if(a.Jd.locationOverrideToken)return{locationOverrideToken:a.Jd.locationOverrideToken};
if(null!=a.Jd.latitudeE7&&null!=a.Jd.longitudeE7)return{latitudeE7:a.Jd.latitudeE7,longitudeE7:a.Jd.longitudeE7}}return null},XCa=function(a,b,c,d){var e=new g.Hm(null,void 0);
a&&g.Im(e,a);b&&g.Jm(e,b);c&&g.Km(e,c);d&&g.Lm(e,d);return e},YCa=function(a){g.eG[a]&&(a=g.eG[a],(0,g.D)(a,function(a){g.cG[a]&&delete g.cG[a]}),a.length=0)},ZCa=function(a){var b=g.bG();
if(b)if(b.clear(a),a)YCa(a);else for(var c in g.eG)YCa(c)},k6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Bm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$Ca(this,a.capabilities||""),aDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},$Ca=function(a,b){a.capabilities.clear();
(0,g.Ud)(b.split(","),g.Fa(TCa,bDa)).forEach(function(b){a.capabilities.add(b)})},aDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},l6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},cDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},dDa=function(a){return new l6(a)},eDa=function(a){return g.za(a)?(0,g.I)(a,dDa):[]},n6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},o6=function(a){return g.za(a)?"["+(0,g.I)(a,n6).join(",")+"]":"null"},p6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},fDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},q6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},r6=function(a,b){return g.Ka(a,function(a){return m6(a,b)})},gDa=function(){var a=(0,g.cH)();
a&&VCa(a,a.o.ee(!0))},s6=function(){var a=g.fH("yt-remote-connected-devices")||[];
g.fb(a);return a},hDa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},iDa=function(a){g.eH("yt-remote-connected-devices",a,86400)},u6=function(){if(t6)return t6;
var a=g.fH("yt-remote-device-id");a||(a=p6(),g.eH("yt-remote-device-id",a,31536E3));for(var b=s6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return t6=d},v6=function(){var a=s6(),b=u6();
g.Oa(a,b);g.hH()&&g.ib(a,b);a=hDa(a);if(g.Pa(a))try{g.NG("remote_sid")}catch(c){}else try{g.MG("remote_sid",a.join(","),-1)}catch(c){}},jDa=function(){return g.fH("yt-remote-session-browser-channel")},kDa=function(){return g.fH("yt-remote-local-screens")||[]},lDa=function(){g.eH("yt-remote-lounge-token-expiration",!0,86400)},mDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(kDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.pm)(c,function(a){return!g.Oa(b,a)})&&lDa();
g.eH("yt-remote-local-screens",a,31536E3)},nDa=function(a,b){g.eH("yt-remote-session-browser-channel",a);
g.eH("yt-remote-session-screen-id",b);var c=s6(),d=u6();g.Oa(c,d)||c.push(d);iDa(c);v6()},w6=function(a){a||(g.gH("yt-remote-session-screen-id"),g.gH("yt-remote-session-video-id"));
v6();a=s6();g.Ta(a,u6());iDa(a)},oDa=function(){if(!x6){var a=g.AD();
a&&(x6=new g.jD(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},pDa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},qDa=function(a,b){var c=g.Nd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.jd(c,g.le("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},rDa=function(){var a=pDa(),b=window.document.getElementById(a),c=b&&g.mF(b,"loaded");
c||b&&!c||(b=qDa(a,function(){g.mF(b,"loaded")||(g.lF(b,"loaded","true"),g.iG(a),g.iE(g.Fa(ZCa,a),0))}))},y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},sDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},z6=function(a){a.length?tDa(a.shift(),function(){z6(a)}):A6()},uDa=function(a){return"chrome-extension://"+a+B6},tDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},C6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},A6=function(){var a=sDa();
a&&a(!1,"No cast extension found")},D6=function(){if(vDa){var a=2,b=sDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;tDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",A6,c)}},wDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(D6(),a({command:"cast.sender.init"}))},xDa=function(){D6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+B6,"//www.gstatic.com/eureka/clank"+B6])},E6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Cd=b;this.D=(0,g.B)(this.xL,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},F6=function(){},G6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.Xm(this);this.A=new g.Cg;this.A.setInterval(250)},zDa=function(a,b,c){a.yk=1;
a.Rh=i6(b.clone());a.Cj=c;a.D=!0;yDa(a,null)},H6=function(a,b,c,d,e){a.yk=1;
a.Rh=i6(b.clone());a.Cj=null;a.D=c;e&&(a.GF=!1);yDa(a,d)},yDa=function(a,b){a.rl=(0,g.H)();
I6(a);a.xi=a.Rh.clone();j6(a.xi,"t",a.F);a.Xn=0;a.Vc=a.o.wt(a.o.On()?b:null);0<a.cu&&(a.Vq=new g.gl((0,g.B)(a.XG,a,a.Vc),a.cu));a.Z.W(a.Vc,"readystatechange",a.MW);var c=a.cj?g.dc(a.cj):{};a.Cj?(a.Pr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Vc.send(a.xi,a.Pr,a.Cj,c)):(a.Pr="GET",a.GF&&!g.Jd&&(c.Connection="close"),a.Vc.send(a.xi,a.Pr,null,c));a.o.Kf(1)},CDa=function(a,b,c){for(var d=!0;!a.Oi&&a.Xn<c.length;){var e=ADa(a,c);
if(e==J6){4==b&&(a.Sh=4,K6(15),d=!1);break}else if(e==BDa){a.Sh=4;K6(16);d=!1;break}else L6(a,e)}4==b&&0==c.length&&(a.Sh=1,K6(17),d=!1);a.Rf=a.Rf&&d;d||(M6(a),N6(a))},ADa=function(a,b){var c=a.Xn,d=b.indexOf("\n",c);
if(-1==d)return J6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return BDa;d+=1;if(d+c>b.length)return J6;var e=b.substr(d,c);a.Xn=d+c;return e},EDa=function(a,b){a.rl=(0,g.H)();
I6(a);var c=b?window.location.hostname:"";a.xi=a.Rh.clone();g.Qm(a.xi,"DOMAIN",c);g.Qm(a.xi,"t",a.F);try{a.Sf=new window.ActiveXObject("htmlfile")}catch(n){M6(a);a.Sh=7;K6(22);N6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O6)k=O6[l];else if(l in DDa)k=O6[l]=DDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=O6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.Bc("b/12014412"),d+"</body></html>");a.Sf.open();a.Sf.write(g.bd(c));a.Sf.close();a.Sf.parentWindow.m=(0,g.B)(a.UV,a);a.Sf.parentWindow.d=(0,g.B)(a.OE,a,!0);a.Sf.parentWindow.rpcClose=(0,g.B)(a.OE,a,!1);c=a.Sf.createElement("DIV");a.Sf.parentWindow.document.body.appendChild(c);d=g.Pc(a.xi.toString());d=g.rb(g.Mc(d));d=g.kd(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Kf(1)},
I6=function(a){a.Lx=(0,g.H)()+a.C;
FDa(a,a.C)},FDa=function(a,b){if(null!=a.Il)throw Error("WatchDog timer not null");
a.Il=P6((0,g.B)(a.kW,a),b)},Q6=function(a){a.Il&&(g.x.clearTimeout(a.Il),a.Il=null)},N6=function(a){a.o.SA()||a.Oi||a.o.Fq(a)},M6=function(a){Q6(a);
g.lf(a.Vq);a.Vq=null;a.A.stop();g.cn(a.Z);if(a.Vc){var b=a.Vc;a.Vc=null;b.abort();b.dispose()}a.Sf&&(a.Sf=null)},L6=function(a,b){try{a.o.GE(a,b),a.o.Kf(4)}catch(c){}},HDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;GDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){HDa(a,b,c,d,f)},f)})}},GDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{R6(d),c(!0)}catch(e){}};
d.onerror=function(){try{R6(d),c(!1)}catch(e){}};
d.onabort=function(){try{R6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},R6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},IDa=function(a){this.o=a;
this.A=new F6},JDa=function(a){var b=S6(a.o,a.Tl,"/mail/images/cleardot.gif");
i6(b);HDa(b.toString(),5E3,(0,g.B)(a.CK,a),3,2E3);a.Kf(1)},U6=function(a){var b=a.o.J;
if(null!=b)K6(5),b?(K6(11),T6(a.o,a,!1)):(K6(12),T6(a.o,a,!0));else if(a.Je=new G6(a,void 0,void 0,void 0),a.Je.cj=a.au,b=a.o,b=S6(b,b.On()?a.Hm:null,a.bu),K6(5),!g.Hd||g.tc(10))j6(b,"TYPE","xmlhttp"),H6(a.Je,b,!1,a.Hm,!1);else{j6(b,"TYPE","html");var c=a.Je;a=!!a.Hm;c.yk=3;c.Rh=i6(b.clone());EDa(c,a)}},V6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new F6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},KDa=function(a,b){this.o=a;
this.map=b;this.context=null},LDa=function(a){g.nf.call(this,"statevent",a)},MDa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},NDa=function(a){g.nf.call(this,"serverreachability",a)},QDa=function(a){ODa(a);
if(3==a.o){var b=a.yn++,c=a.mp.clone();g.Qm(c,"SID",a.B);g.Qm(c,"RID",b);g.Qm(c,"TYPE","terminate");W6(a,c);b=new G6(a,a.B,b,void 0);b.yk=2;b.Rh=i6(c.clone());(new window.Image).src=b.Rh;b.rl=(0,g.H)();I6(b)}PDa(a)},RDa=function(a){a.YK(1,0);
a.mp=S6(a,null,a.Zt);X6(a)},ODa=function(a){a.Dh&&(a.Dh.abort(),a.Dh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Jg&&(g.x.clearTimeout(a.Jg),a.Jg=null);Y6(a);a.ke&&(a.ke.cancel(),a.ke=null);a.Jh&&(g.x.clearTimeout(a.Jh),a.Jh=null)},SDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new KDa(a.IR++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.ke||a.Jh||(a.Jh=P6((0,g.B)(a.ME,a),0),a.mk=0)},UDa=function(a,b){if(1==a.o){if(!b){a.yn=Math.floor(1E5*Math.random());
var c=a.yn++,d=new G6(a,"",c,void 0);d.cj=null;var e=Z6(a),f=a.mp.clone();g.Qm(f,"RID",c);g.Qm(f,"CVER","1");W6(a,f);zDa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?TDa(a,b):0==a.A.length||a.ke||TDa(a))},TDa=function(a,b){if(b)if(6<a.Qi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.yn-1;var d=Z6(a)}else c=b.G,d=b.Cj;else c=a.yn++,d=Z6(a);var e=a.mp.clone();g.Qm(e,"SID",a.B);g.Qm(e,"RID",c);g.Qm(e,"AID",a.Mk);W6(a,e);c=new G6(a,a.B,c,a.mk+1);c.cj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;zDa(c,e,d)},W6=function(a,b){if(a.Bd){var c=a.Bd.yA();
c&&g.Jb(c,function(a,c){g.Qm(b,c,a)})}},Z6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Qi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Qi?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},VDa=function(a){a.Bc||a.Jg||(a.G=1,a.Jg=P6((0,g.B)(a.LE,a),0),a.Zj=0)},$6=function(a){if(a.Bc||a.Jg||3<=a.Zj)return!1;
a.G++;a.Jg=P6((0,g.B)(a.LE,a),WDa(a,a.Zj));a.Zj++;return!0},T6=function(a,b,c){a.Nr=c;
a.jg=b.Xg;a.F||RDa(a)},Y6=function(a){null!=a.Ri&&(g.x.clearTimeout(a.Ri),a.Ri=null)},WDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Bd&&(c=null);var d=(0,g.B)(a.DX,a);c||(c=new g.Hm("//www.google.com/images/cleardot.gif"),i6(c));GDa(c.toString(),1E4,d)}else K6(2);XDa(a,b)},XDa=function(a,b){a.o=0;
a.Bd&&a.Bd.Bz(b);PDa(a);ODa(a)},PDa=function(a){a.o=0;
a.jg=-1;if(a.Bd)if(0==a.C.length&&0==a.A.length)a.Bd.Vs();else{g.Xa(a.C);var b=g.Xa(a.A);a.C.length=0;a.A.length=0;a.Bd.Vs(b)}},S6=function(a,b,c){var d=g.Rm(c);
if(""!=d.A)b&&g.Jm(d,b+"."+d.A),g.Km(d,d.D);else{var e=window.location;d=XCa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.pm&&g.Jb(a.pm,function(a,b){g.Qm(d,b,a)});
g.Qm(d,"VER",a.Qi);W6(a,d);return d},P6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},K6=function(a){b7.dispatchEvent(new LDa(b7,a))},YDa=function(){},ZDa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.M.call(this);
this.o=new g.lu(this.LV,0,this);g.N(this,this.o);this.Cd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.B)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},d7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.iD;this.A=new c7(this.nY,this);this.o=this.gb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.N=c||!1},$Da=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Nr,sessionId:a.o.B,arrayId:a.o.Mk}},aEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&UDa(a.o),QDa(a.o));a.H=0},e7=function(a){return!!a.o&&3==a.o.o},bEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Sg(a)||"";b&&(this.port=":"+b);this.domain=g.Rg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.A=!1))},g7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.ah(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Gd:g.Fa(a.D,e)};c&&(a.Qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.zE(b,a)},fEa=function(){var a=cEa;
dEa();i7.push(a);eEa(i7)},j7=function(a,b){dEa();
var c=i7,d=gEa(a,String(b));g.Pa(c)?hEa(d):(eEa(c),(0,g.D)(c,function(a){a(d)}))},dEa=function(){i7||(i7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",i7,void 0))},hEa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},eEa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},gEa=function(a,b){var c=((0,g.H)()-iEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.UF.call(this);
this.G=a;this.o=[]},jEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},kEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Ud)(a.o,function(a){return!!q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=jEa(a,b[d])||c;return c},lEa=function(a,b){var c=a.o.length;
a.o=(0,g.Ud)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},o7=function(a,b,c,d){g.UF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;p7(this);this.info("Initializing with "+o6(this.o))},mEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.LL,a),(0,g.B)(a.KL,a))}},p7=function(a){var b=eDa(kDa());
b=(0,g.Ud)(b,function(a){return!a.uuid});
return kEa(a,b)},r7=function(a,b){mDa((0,g.I)(a.o,cDa));
b&&lDa()},t7=function(a,b){g.UF.call(this);
this.F=b;var c=g.fH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;s7("Initialized with "+g.Jg(this.o))},nEa=function(a,b,c){var d=g7(a.D,"/pairing/get_screen_availability");
h7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},u7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Jg(a.o)),a.o=b,a.V("screenChange"));oEa(a)},v7=function(a){(0,window.isNaN)(a.B)||g.kE(a.B);
a.B=g.iE((0,g.B)(a.Qw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},pEa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.jc("Requesting availability of screen w/o lounge token.")});
return b},oEa=function(a){a=g.Rb(g.Kb(a.o,function(a){return a}));
g.fb(a);a.length?g.eH("yt-remote-online-screen-ids",a.join(","),60):g.gH("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};qEa(this)},sEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ce();if(k=(c?r6(k,c):null)||r6(k,b)){k.uuid=b;var l=x7(a,k);nEa(a.A,l,function(a){e(a?l:null)})}else c?rEa(a,c,(0,g.B)(function(a){var f=x7(this,new l6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));nEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},tEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},rEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.zE(g7(a.F,"/pairing/get_lounge_token_batch"),e)},uEa=function(a){a.o=a.B.Ce();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+o6(a.o))},qEa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.ZL,a));uEa(a);a.C=eDa(g.fH("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+o6(a.C));a.A=new t7(a.F,(0,g.B)(a.Ce,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=r6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.eH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,cDa)));y7(a);a.D[b.uuid]=b.id;g.eH("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.fH("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.UF.call(this);
this.N=c;this.J=a;this.A=b;this.B=null},A7=function(a,b){j7(a.N,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.tY,this);this.D=(0,g.B)(this.wW,this);this.C=g.iE((0,g.B)(function(){vEa(this,null)},this),12E4)},wEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Jg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.B)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Jg(b))},vEa=function(a,b){g.kE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Gq,a),d=(0,g.B)(a.Ie,a);a.IA(b,c,d,5)}}else a.Ie(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.B)(this.wY,this);this.o=g.z},xEa=function(a){a.o=a.J.eH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.z;
this.Gq(a)},a),(0,g.B)(function(a){this.o=g.z;
this.Ie(a)},a))},yEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}oDa()&&(b.env_useStageMdx=1);return g.Zg(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.iE((0,g.B)(this.Ok,this,null),150)},E7=function(a,b,c,d){g.UF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.XU,this)},zEa=function(a,b){return b?g.Ka(a.B,function(a){return m6(b,a.label)},a):null},F7=function(a){j7("Controller",a)},cEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},G7=function(a){return a.D||!!a.B.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.lf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.JE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Ok(null)):a.V("yt-remote-cast2-session-change",null))},AEa=function(a){var b=a.A.dH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&m6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=zEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},GEa=function(a,b,c,d,e,f,k){BEa()?CEa(b,e,f,k)&&(J7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?DEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?DEa(a,c):(K7("Failed to load cast API: "+d),L7(!1),J7(!1),g.gH("yt-remote-cast-available"),g.gH("yt-remote-cast-receiver"),EEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):rDa():C6("CriOS")?wDa():C6("Android")&&C6("Chrome/")&&window.navigator.presentation?xDa():window.chrome&&window.navigator.presentation&&!C6("Edge")?(D6(),z6(FEa.map(uDa))):A6())):I7("Cannot initialize because not running Chrome")},EEa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);HEa(!1);g.gG(N7);N7.length=0},O7=function(){return!!g.fH("yt-remote-cast-installed")},IEa=function(){var a=g.fH("yt-remote-cast-receiver");
return a?a.friendlyName:null},JEa=function(){I7("clearCurrentReceiver");
g.gH("yt-remote-cast-receiver")},KEa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.fG("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},BEa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.vI||a},LEa=function(a,b){M7().init(a,b)},CEa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.eH("yt-remote-cast-available",a);g.jG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){I7("onReceiverSelected: "+a.friendlyName);
g.eH("yt-remote-cast-receiver",a);g.jG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){I7("onReceiverResumed: "+a.friendlyName);
g.eH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){I7("onSessionChange: "+n6(a));
a||g.gH("yt-remote-cast-receiver");g.jG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},DEa=function(a,b){L7(!0);
J7(!1);LEa(a,function(a){a?(HEa(!0),g.iG("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.gH("yt-remote-cast-available"),g.gH("yt-remote-cast-receiver"),EEa());b(a)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.eH("yt-remote-cast-installed",a)},P7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},HEa=function(a){I7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.ng=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.ng=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},U7=function(a){return a.rb()?((0,g.H)()-a.G)/1E3:0},V7=function(a,b){a.H=b;
a.G=(0,g.H)()},W7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.ng;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},$7=function(a,b){g.UF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.yC;this.B=this.A=null;this.J=(0,g.B)(this.rS,this);this.G=(0,g.B)(this.Bn,this);this.H=(0,g.B)(this.qS,this);this.K=(0,g.B)(this.DS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Sx,this),MEa(this))):c=3;0!=c&&(b?this.Sx(c):g.iE((0,g.B)(function(){this.Sx(c)},this),0));
var d=KEa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},a8=function(a){return new S7(a.C.getPlayerContextData())},MEa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.SU,a),this))},a)},NEa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},b8=function(a,b){50>a.D.Cc()&&g.AC(a.D,b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.o&&(d.o=b);c8(a,d)},e8=function(a,b,c){a.C.sendMessage(b,c)},c8=function(a,b){NEa(a);
a.C.setPlayerContextData(Y7(b));MEa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Bn(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Bn(a.B.media[0]))},OEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;V7(d,a.A.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.B)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.UF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.N=window.NaN;this.Y=[];this.C=this.G=this.B=this.ib=this.o=null;this.ua=a;this.Y.push(g.DF(window,"beforeunload",(0,g.B)(this.BL,this)));this.A=[];this.ib=new S7;this.ca=b.id;this.o=PEa(this,c);this.o.subscribe("handlerOpened",this.vS,this);this.o.subscribe("handlerClosed",this.sS,this);this.o.subscribe("handlerError",this.tS,this);this.o.subscribe("handlerMessage",this.uS,this);bEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.ib.videoId;g.hH()&&g.eH("yt-remote-session-video-id",a)},this)},h8=function(a){j7("conn",a)},PEa=function(a,b){return new d7(g7(a.ua,"/bc"),b)},i8=function(a,b){a.V("proxyStateChange",b)},QEa=function(a){a.D=g.iE((0,g.B)(function(){h8("Connecting timeout");
this.F(1)},a),2E4)},j8=function(a){g.kE(a.D);
a.D=window.NaN},k8=function(a){g.kE(a.N);
a.N=window.NaN},REa=function(a){l8(a);
a.L=g.iE((0,g.B)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.kE(a.L);
a.L=window.NaN},TEa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&(0,window.isNaN)(a.D))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.aa()&&a.ib.reset(),i8(a,1),m8(a,"getNowPlaying"),SEa(a)):a.F(1)},UEa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Zb(b.params)?a.ib.A=null:a.ib.A=b.params,a.V("remotePlayerChange"))},VEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;X7(a.ib,c,d);a.V("remoteQueueChange")},XEa=function(a,b){b.params=b.params||{};
VEa(a,b);WEa(a,b);a.V("autoplayDismissed")},WEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
V7(a.ib,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.ib.o&&(c=-1E3);a.ib.o=c;c=Number(b.params.loadedTime);a.ib.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.ib.J=(0,window.isNaN)(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.ib.o?REa(a):l8(a);
a.V("remotePlayerChange")},YEa=function(a,b){if(-1E3!=a.ib.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.o=c;c=(0,window.parseInt)(b.params.currentTime,10);V7(a.ib,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},ZEa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=(0,window.parseInt)(b.params.volume,10);a.ib.muted=c;a.V("remotePlayerChange")},$Ea=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},aFa=function(a,b){var c="true"==b.params.hasNext;
a.ib.ng="true"==b.params.hasPrevious;a.ib.hasNext=c;a.V("previousNextChange")},SEa=function(a){g.kE(a.K);
a.K=g.iE((0,g.B)(a.F,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Jg(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.B)(this.rY,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.B)(this.sU,this)))},fFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.cE("MDX_CONFIG")||b;gDa();v6();o8||(o8=new f7(b?b.loungeApiHost:void 0),oDa()&&(o8.o="/api/loungedev"));p8||(p8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",p8,void 0));bFa();var c=q8();if(!c){var d=new w7(o8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);GEa(a,d,function(a){a?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.jG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Jg(b)),t8.push(g.fG("yt-remote-cast2-availability-change",function(){g.jG("yt-remote-receiver-availability-change")})),t8.push(g.fG("yt-remote-cast2-receiver-selected",function(){u8(null);
g.jG("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.fG("yt-remote-cast2-receiver-resumed",function(){g.jG("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.fG("yt-remote-cast2-session-change",cFa)),t8.push(g.fG("yt-remote-connection-change",function(a){a?R7(r8(),"YouTube TV"):v8()||(R7(null,null),JEa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.$F("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),s8(" -- with channel params: "+
g.Jg(a)),dFa(a),c.start(),r8()||eFa())},hFa=function(){var a=gFa();
O7()&&g.fH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},gFa=function(){var a=q8().ld.$_gos();
var b=x8();b&&y8()&&(q6(a,b)||a.push(b));return fDa(a)},z8=function(){var a=iFa();
!a&&O7()&&IEa()&&(a={key:"cast-selector-receiver",name:IEa()});return a},iFa=function(){var a=gFa(),b=x8();
b||(b=v8());return g.Ka(a,function(a){return b&&m6(b,a.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Ce();return r6(b,a)},cFa=function(a){s8("remote.onCastSessionChange_: "+n6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.y("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.y("yt.mdx.remote.currentScreenId_")},jFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},kFa=function(){return g.y("yt.mdx.remote.connectData_")},u8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.y("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||jFa("");g.ua("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.D)(p8,function(b){b(a)}),p8.length=0);
b&&!a?g.jG("yt-remote-connection-change",!1):!b&&a&&g.jG("yt-remote-connection-change",!0)},v8=function(){var a=g.hH();
if(!a)return null;var b=q8().Ce();return r6(b,a)},B8=function(a,b){x8()&&x8();
jFa(a.id);var c=new g8(o8,a,w8());c.connect(b,kFa());c.subscribe("beforeDisconnect",function(a){g.jG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y8()&&C8(null)});
C8(c)},eFa=function(){var a=v8();
a?(s8("Resume connection to: "+n6(a)),B8(a,0)):(w6(),JEa(),s8("Skipping connecting because no session screen found."))},bFa=function(){var a=w8();
if(g.Zb(a)){a=u6();var b=g.fH("yt-remote-session-name")||"",c=g.fH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},dFa=function(a){a?(g.eH("yt-remote-session-app",a.app),g.eH("yt-remote-session-name",a.name)):(g.gH("yt-remote-session-app"),g.gH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.M.call(this);
this.G=a;this.T=b;this.A=new g.RF(this);g.N(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.KT);this.A.R(b,"captionschanged",this.pS);this.A.R(b,"captionssettingschanged",this.pG);this.A.R(b,"videoplayerreset",this.Hq);this.A.R(b,"mdxautoplaycancel",this.BK);this.O=this.A.R(b,"onVolumeChange",this.qE);this.F=!1;this.o=c;c.subscribe("proxyStateChange",this.FE,this);c.subscribe("remotePlayerChange",this.En,this);c.subscribe("remoteQueueChange",this.Hq,this);c.subscribe("autoplayUpNext",this.bE,
this);c.subscribe("previousNextChange",this.CE,this);c.subscribe("nowAutoplaying",this.tE,this);c.subscribe("autoplayDismissed",this.aE,this);this.suggestion=null;this.H=new g.VP(64);this.B=new g.lu(this.lG,500,this);g.N(this,this.B);this.C=new g.lu(this.mG,1E3,this);g.N(this,this.C);this.K=new E6(this.SX,0,this);g.N(this,this.K);this.D={};this.L=new g.lu(this.LG,1E3,this);g.N(this,this.L);this.J=new g.gl(this.tQ,1E3,this);g.N(this,this.J);this.N=g.z;this.pG();this.Hq();this.En()},G8=function(a,b){var c=
a.G,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},lFa=function(a){G8(a,0);
a.B.stop();H8(a,new g.VP(64))},J8=function(a,b){if(I8(a)&&!a.F){var c=null;
b&&(c={style:a.T.vj()},g.gc(c,b));a.o.aG(a.T.getVideoData(1).videoId,c);a.D=a8(a.o).A}},K8=function(a,b){var c=a.T.vg();
if(c){var d=c.Ae();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Hk;f=WCa(f);var n=a8(c);l=l||0;var p={videoId:k,currentIndex:l};X7(n,k,l);g.u(b)&&(V7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Jg(f));e8(c,"setPlaylist",p);e||c8(c,n);H8(a,new g.VP(1))},mFa=function(a,b){if(b){var c=a.T.Fc("captions","tracklist",{CB:1});
c&&c.length?(a.T.Vd("captions","track",b),a.F=!1):(a.T.Wk("captions"),a.F=!0)}else a.T.Vd("captions","track",{})},I8=function(a){return a8(a.o).videoId==a.T.getVideoData(1).videoId},H8=function(a,b){a.C.stop();
var c=a.H;if(!g.$P(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.fU(a.T,d);a.H=b;nFa(a.G,c,b)}},L8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.Cqa()]},{I:"div",M:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.fV(this,250);g.N(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);oFa(this,g.aU(a))},oFa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Fc("remote","currentReceiver").name};
c=g.X(b,128)?g.f0("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):b.rb()||g.X(b,4)?g.f0("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.f0("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},M8=function(a,b){g.CY.call(this,"Reproducir en",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},N8=function(a){g.GU.call(this,a);
this.B={key:p6(),name:"Este ordenador"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.VP(64);this.J=0;if(!g.ZM(g.Y(this.o))){a=this.o;var b=g.XH(a);b&&(b=b.pn())&&(b=new M8(a,b),g.N(this,b));b=new L8(a);g.N(this,b);g.wU(a,b.element,4)}},nFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.eQ(c,b))},O8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)A8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.vg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Zb(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Hk,index:Math.max(a.o.EC(),0),currentTime:0==f?void 0:f};(d=WCa(d))&&(c.locationInfo=d);d=c}else d=null;s8("Connecting to: "+g.Jg(b));"cast-selector-receiver"==b.key?(u8(d||null),P7()?M7().setLaunchParams(d||null):
K7("setLaunchParams called before ready.")):!d&&D8()&&r8()==b.key?g.jG("yt-remote-connection-change",!0):(A8(),u8(d||null),d=q8().Ce(),(d=r6(d,b.key))&&B8(d,1))}},DDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},O6={"'":"\\'"},pFa={},bDa={GZ:"atp",n4:"ska",C3:"que",O2:"mus",i4:"sus",Q0:"dsp"};
k6.prototype.So=function(){var a=new k6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var x6,t6="",B6=y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",vDa=y6("loadCastFramework")||y6("loadCastApplicationFramework"),FEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(E6,g.M);g.h=E6.prototype;g.h.wL=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.H)()+this.Cd:this.Ea=g.Dg(this.D,this.Cd)};
g.h.stop=function(){this.Ea&&(g.Eg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();E6.fa.X.call(this)};
g.h.xL=function(){this.B?(this.Ea=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};F6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
F6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=G6.prototype;g.h.cj=null;g.h.Rf=!1;g.h.Il=null;g.h.Lx=null;g.h.rl=null;g.h.yk=null;g.h.Rh=null;g.h.xi=null;g.h.Cj=null;g.h.Vc=null;g.h.Xn=0;g.h.Sf=null;g.h.Pr=null;g.h.Sh=null;g.h.Im=-1;g.h.GF=!0;g.h.Oi=!1;g.h.cu=0;g.h.Vq=null;var BDa={},J6={};g.h=G6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.MW=function(a){a=a.target;var b=this.Vq;b&&3==g.ux(a)?b.Em():this.XG(a)};
g.h.XG=function(a){try{if(a==this.Vc)a:{var b=g.ux(this.Vc),c=this.Vc.A,d=this.Vc.getStatus();if(g.Hd&&!g.tc(10)||g.Jd&&!g.sc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pf&&!g.yx(this.Vc))break a;this.Oi||4!=b||7==c||(8==c||0>=d?this.o.Kf(3):this.o.Kf(2));Q6(this);var e=this.Vc.getStatus();this.Im=e;var f=g.yx(this.Vc);(this.Rf=200==e)?(4==b&&M6(this),this.D?(CDa(this,b,f),g.pf&&this.Rf&&3==b&&(this.Z.W(this.A,"tick",this.IW),this.A.start())):L6(this,f),this.Rf&&!this.Oi&&(4==b?this.o.Fq(this):
(this.Rf=!1,I6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Sh=3,K6(13)):(this.Sh=0,K6(14)),M6(this),N6(this))}}catch(k){this.Vc&&g.yx(this.Vc)}finally{}};
g.h.IW=function(){var a=g.ux(this.Vc),b=g.yx(this.Vc);this.Xn<b.length&&(Q6(this),CDa(this,a,b),this.Rf&&4!=a&&I6(this))};
g.h.UV=function(a){P6((0,g.B)(this.TV,this,a),0)};
g.h.TV=function(a){this.Oi||(Q6(this),L6(this,a),I6(this))};
g.h.OE=function(a){P6((0,g.B)(this.SV,this,a),0)};
g.h.SV=function(a){this.Oi||(M6(this),this.Rf=a,this.o.Fq(this),this.o.Kf(4))};
g.h.cancel=function(){this.Oi=!0;M6(this)};
g.h.kW=function(){this.Il=null;var a=(0,g.H)();0<=a-this.Lx?(2!=this.yk&&this.o.Kf(3),M6(this),this.Sh=2,K6(18),N6(this)):FDa(this,this.Lx-a)};g.h=IDa.prototype;g.h.au=null;g.h.Je=null;g.h.Wq=!1;g.h.TA=null;g.h.ip=null;g.h.Vu=null;g.h.bu=null;g.h.bf=null;g.h.Xg=-1;g.h.Hm=null;g.h.Tl=null;g.h.connect=function(a){this.bu=a;a=S6(this.o,null,this.bu);K6(3);this.TA=(0,g.H)();var b=this.o.H;null!=b?(this.Hm=b[0],(this.Tl=b[1])?(this.bf=1,JDa(this)):(this.bf=2,U6(this))):(j6(a,"MODE","init"),this.Je=new G6(this,void 0,void 0,void 0),this.Je.cj=this.au,H6(this.Je,a,!1,null,!0),this.bf=0)};
g.h.CK=function(a){if(a)this.bf=2,U6(this);else{K6(4);var b=this.o;b.jg=b.Dh.Xg;a7(b,9)}a&&this.Kf(2)};
g.h.wt=function(a){return this.o.wt(a)};
g.h.abort=function(){this.Je&&(this.Je.cancel(),this.Je=null);this.Xg=-1};
g.h.SA=function(){return!1};
g.h.GE=function(a,b){this.Xg=a.Im;if(0==this.bf)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.jg=this.Xg;a7(c,2);return}this.Hm=c[0];this.Tl=c[1]}else c=this.o,c.jg=this.Xg,a7(c,2);else if(2==this.bf)if(this.Wq)K6(7),this.Vu=(0,g.H)();else if("11111"==b){if(K6(6),this.Wq=!0,this.ip=(0,g.H)(),c=this.ip-this.TA,!g.Hd||g.tc(10)||500>c)this.Xg=200,this.Je.cancel(),K6(12),T6(this.o,this,!0)}else K6(8),this.ip=this.Vu=(0,g.H)(),this.Wq=!1};
g.h.Fq=function(){this.Xg=this.Je.Im;if(this.Je.Rf)0==this.bf?this.Tl?(this.bf=1,JDa(this)):(this.bf=2,U6(this)):2==this.bf&&((!g.Hd||g.tc(10)?!this.Wq:200>this.Vu-this.ip)?(K6(11),T6(this.o,this,!1)):(K6(12),T6(this.o,this,!0)));else{0==this.bf?K6(9):2==this.bf&&K6(10);var a=this.o;a.jg=this.Xg;a7(a,2)}};
g.h.On=function(){return this.o.On()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Kf=function(a){this.o.Kf(a)};g.h=V6.prototype;g.h.pm=null;g.h.ke=null;g.h.Bc=null;g.h.Zt=null;g.h.mp=null;g.h.pz=null;g.h.Bp=null;g.h.yn=0;g.h.IR=0;g.h.Bd=null;g.h.Jh=null;g.h.Jg=null;g.h.Ri=null;g.h.Dh=null;g.h.Nr=null;g.h.Mk=-1;g.h.RB=-1;g.h.jg=-1;g.h.mk=0;g.h.Zj=0;g.h.Qi=8;var b7=new g.Of;g.C(LDa,g.nf);g.C(MDa,g.nf);g.C(NDa,g.nf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){K6(0);this.Zt=b;this.pm=c||{};d&&g.u(e)&&(this.pm.OSID=d,this.pm.OAID=e);this.F?(P6((0,g.B)(this.Lz,this,a),100),RDa(this)):this.Lz(a)};
g.h.Lz=function(a){this.Dh=new IDa(this);this.Dh.au=null;this.Dh.A=this.D;this.Dh.connect(a)};
g.h.SA=function(){return 0==this.o};
g.h.ME=function(a){this.Jh=null;UDa(this,a)};
g.h.LE=function(){this.Jg=null;this.Bc=new G6(this,this.B,"rpc",this.G);this.Bc.cj=null;this.Bc.cu=0;var a=this.pz.clone();g.Qm(a,"RID","rpc");g.Qm(a,"SID",this.B);g.Qm(a,"CI",this.Nr?"0":"1");g.Qm(a,"AID",this.Mk);W6(this,a);if(!g.Hd||g.tc(10))g.Qm(a,"TYPE","xmlhttp"),H6(this.Bc,a,!0,this.Bp,!1);else{g.Qm(a,"TYPE","html");var b=this.Bc,c=!!this.Bp;b.yk=3;b.Rh=i6(a.clone());EDa(b,c)}};
g.h.GE=function(a,b){if(0!=this.o&&(this.Bc==a||this.ke==a))if(this.jg=a.Im,this.ke==a&&3==this.o)if(7<this.Qi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Jg){if(this.Bc)if(this.Bc.rl+3E3<this.ke.rl)Y6(this),this.Bc.cancel(),this.Bc=null;else break a;$6(this);K6(19)}}else this.RB=c[1],0<this.RB-this.Mk&&37500>c[2]&&this.Nr&&0==this.Zj&&!this.Ri&&(this.Ri=P6((0,g.B)(this.kS,this),6E3));else a7(this,11)}else b!=pFa.J_.o&&a7(this,11);else if(this.Bc==a&&
Y6(this),!g.F(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Mk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Bp=e[2],e=e[3],null!=e?this.Qi=e:this.Qi=6,this.o=3,this.Bd&&this.Bd.Dz(),this.pz=S6(this,this.On()?this.Bp:null,this.Zt),VDa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Bd&&this.Bd.Cz(e),this.Zj=0)}}};
g.h.kS=function(){null!=this.Ri&&(this.Ri=null,this.Bc.cancel(),this.Bc=null,$6(this),K6(20))};
g.h.Fq=function(a){if(this.Bc==a){Y6(this);this.Bc=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.jg=a.Im;if(0!=this.o)if(a.Rf)1==b?(b=(0,g.H)()-a.rl,b7.dispatchEvent(new MDa(b7,a.Cj?a.Cj.length:0,b,this.mk)),X6(this),this.C.length=0):VDa(this);else{var c=a.Sh,d;if(!(d=3==c||7==c||0==c&&0<this.jg)){if(d=1==b)this.ke||this.Jh||1==this.o||2<=this.mk?d=!1:(this.Jh=P6((0,g.B)(this.ME,this,a),WDa(this,this.mk)),this.mk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,5);
break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.h.YK=function(a){if(!g.Oa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.DX=function(a){a?K6(2):(K6(1),XDa(this,8))};
g.h.wt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.ox;a.H=!1;return a};
g.h.isActive=function(){return!!this.Bd&&this.Bd.isActive(this)};
g.h.Kf=function(a){b7.dispatchEvent(new NDa(b7,a))};
g.h.On=function(){return!(!g.Hd||g.tc(10))};
g.h=YDa.prototype;g.h.Dz=function(){};
g.h.Cz=function(){};
g.h.Bz=function(){};
g.h.Vs=function(){};
g.h.yA=function(){return{}};
g.h.isActive=function(){return!0};g.C(c7,g.M);g.h=c7.prototype;g.h.LV=function(){this.Cd=Math.min(3E5,2*this.Cd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Cd+15E3*Math.random();g.mu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Cd=5E3};g.C(d7,YDa);g.h=d7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.be=function(a){return this.B.be(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.lf(this.B),aEa(this),g.lf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Bd=null);d.Bd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Mk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&SDa(this.o,c)};
g.h.Dz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)SDa(this.o,a[b])}this.V("handlerOpened")};
g.h.Bz=function(a){var b=2==a&&401==this.o.jg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Vs=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.yA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.Cz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),QDa(this.o)):this.V("handlerMessage",new ZDa(a[0],a[1]))};
g.h.nY=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};f7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.D=function(a){a(Error("request timed out"))};var iEa=(0,g.H)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.C(n7,g.UF);n7.prototype.Ce=function(){return this.o};
n7.prototype.contains=function(a){return!!q6(this.o,a)};
n7.prototype.get=function(a){return a?r6(this.o,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.C(o7,g.UF);var qFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=o7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.cH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.kE(this.Ea),this.Ea=window.NaN)};
g.h.X=function(){this.stop();o7.fa.X.call(this)};
g.h.cH=function(){this.Ea=window.NaN;this.o=g.zE(g7(this.F,"/pairing/get_screen"),{method:"POST",Qb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.pY,this),onError:(0,g.B)(this.oY,this),Gd:(0,g.B)(this.qY,this)})};
g.h.pY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new l6(c))};
g.h.oY=function(a){this.o=null;a.status&&404==a.status?this.A>=qFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=qFa[this.A],this.Ea=g.iE((0,g.B)(this.cH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.qY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(q7,n7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.V("screenChange");!g.fH("yt-remote-lounge-token-expiration")&&mEa(this);g.kE(this.A);this.A=g.iE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);jEa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||mEa(this)};
g.h.remove=function(a,b){var c=p7(this);lEa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Ir=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.kE(this.A);q7.fa.X.call(this)};
g.h.LL=function(a){p7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.h.KL=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.C(t7,g.UF);g.h=t7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.fH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?v7(this):(this.C=(0,g.H)()+3E5,g.eH("yt-remote-fast-check-period",this.C),this.Qw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Kb(this.o,function(b,d){return b&&!!r6(a,d)},this);
u7(this,b)};
g.h.X=function(){g.kE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);t7.fa.X.call(this)};
g.h.Qw=function(){g.kE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=pEa(this);if(g.Ob(a)){var b=g7(this.D,"/pairing/get_screen_availability");this.A=h7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.B)(this.sV,this,a),(0,g.B)(this.rV,this))}else u7(this,{}),v7(this)};
g.h.sV=function(a,b){this.A=null;var c=g.Rb(pEa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.jc("Changing Screen set during request."),this.Qw()};
g.h.rV=function(a){this.jc("Screen availability failed: "+a);this.A=null;v7(this)};
g.h.jc=function(a){j7("OnlineScreenService",a)};g.C(w7,n7);g.h=w7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Ir=function(a,b,c,d){this.B.contains(a)?this.B.Ir(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.h.Ce=function(a){return a?this.o:g.Wa(this.o,(0,g.Ud)(this.C,function(a){return!this.contains(a)},this))};
g.h.dH=function(){return(0,g.Ud)(this.Ce(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.eH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.lf(f);d(x7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.sY=function(a,b,c,d){g.zE(g7(this.F,"/pairing/get_screen"),{method:"POST",Qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new l6(d.screen||{});if(!e.name||tEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);tEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(x7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Gd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.lf(this.B);g.lf(this.A);w7.fa.X.call(this)};
g.h.ZL=function(){uEa(this);this.V("screenChange");this.A.update()};
w7.prototype.dispose=w7.prototype.dispose;g.C(z7,g.UF);g.h=z7.prototype;g.h.Gq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ie=function(a){this.la()||(a&&A7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){j7(this.N,a)};
g.h.gH=function(){return null};
g.h.Ww=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Ww("");z7.fa.X.call(this)};g.C(B7,z7);g.h=B7.prototype;g.h.Vw=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);wEa(this)};
g.h.Ok=function(a){this.info("launchWithParams no-op for Cast: "+g.Jg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Ie()},this),(0,g.B)(function(){this.Ie(Error("Failed to stop receiver app."))},this)):this.Ie(Error("Stopping cast device witout session."))};
g.h.Ww=g.z;g.h.X=function(){this.info("disposeInternal");g.kE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;B7.fa.X.call(this)};
g.h.wW=function(a,b){if(!this.la())if(b){var c=g.ix(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Jg(c));switch(d){case "mdxSessionStatus":vEa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.h.IA=function(a,b,c,d){sEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.iE((0,g.B)(this.IA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.gH=function(){return this.o};
g.h.tY=function(a){this.la()||a||(A7(this,"Cast session died."),this.Ie())};g.C(C7,z7);g.h=C7.prototype;g.h.Vw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Ok=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.kE(this.F);this.C?this.C.stop((0,g.B)(this.Ie,this,null),(0,g.B)(this.Ie,this,"Failed to stop DIAL device.")):this.Ie()};
g.h.X=function(){this.o();this.o=g.z;g.kE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;C7.fa.X.call(this)};
g.h.wY=function(a){this.la()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.z,this.Ie())};
g.h.Iu=function(a){this.K=p6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,yEa(this));a(b);xEa(this)}else this.G=(0,g.B)(function(){g.kE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,yEa(this));a(b);xEa(this)},this),this.F=g.iE((0,g.B)(function(){this.G()},this),100)};
g.h.nN=function(a,b,c){sEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Gq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Iu(b,c)},this),(0,g.B)(function(a){A7(this,"Failed to get DIAL screen: "+a);
this.Iu(b,c)},this))};g.C(D7,z7);D7.prototype.stop=function(){this.Ie()};
D7.prototype.Vw=g.z;D7.prototype.Ok=function(){g.kE(this.o);this.o=window.NaN;var a=r6(this.J.Ce(),this.A.label);a?this.Gq(a):this.Ie(Error("No such screen"))};
D7.prototype.X=function(){g.kE(this.o);this.o=window.NaN;D7.fa.X.call(this)};g.C(E7,g.UF);g.h=E7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.IE,this),(0,g.B)(this.bV,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.VS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),fEa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.fH,this)),this.B=AEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(a){this.jc("Failed to set initial custom receivers: "+g.Jg(a))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.B)(function(a){this.jc("Failed to initialize API: "+g.Jg(a));
b(!1)},this))};
g.h.lX=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.A.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=r6(this.A.Ce(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=zEa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(a){this.jc("Failed to set initial custom receivers: "+g.Jg(a))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.A,d),!0)}this.o.Ww(b)}else F7("setConnectedScreenStatus: no screen.")};
g.h.mX=function(a){this.la()?this.jc("Setting connection data on disposed cast v2"):this.o?this.o.Ok(a):this.jc("Setting connection data without a session")};
g.h.vY=function(){this.la()?this.jc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.IE,this),(0,g.B)(this.wV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.fH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],cEa);g.lf(this.o);E7.fa.X.call(this)};
g.h.jc=function(a){j7("Controller",a)};
g.h.JE=function(a,b){this.o==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.XU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:H7(this,new B7(this.A,a));break;default:this.jc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.jc("Stopping receiver w/o session: "+a.friendlyName)}else this.jc("onReceiverAction_ called without receiver.")};
g.h.VS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.jc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.jc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.jc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.nN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Iu,b))};
g.h.IE=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.A,b),!0);else{this.jc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=r6(this.A.Ce(),c.label);
d&&m6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.o),this.o=new B7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.JE,this,this.o)),this.o.Ok(null));this.o.Vw(a)}}};
g.h.uY=function(){return this.o?this.o.gH():null};
g.h.wV=function(a){this.la()||(this.jc("Failed to estabilish a session: "+g.Jg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.h.bV=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.h.fH=function(){this.la()||(this.B=AEa(this),F7("Updating custom receivers: "+g.Jg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(){this.jc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.mX;E7.prototype.setConnectedScreenStatus=E7.prototype.lX;E7.prototype.stopSession=E7.prototype.vY;E7.prototype.getCastSession=E7.prototype.uY;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.h=S7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.ng=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+U7(this):this.J};
g.h.clone=function(){return new S7(Y7(this))};g.C($7,g.UF);g.h=$7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.pause)};
g.h.bH=function(a){if(1==this.o){if(this.A){var b=a8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.V("remotePlayerChange")}else b8(this,g.Fa(this.bH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.V("remotePlayerChange")}else b8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Fa(this.setVolume,a,b))};
g.h.aG=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Jg(b.style),g.gc(d,c.A));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Fa(this.aG,a,b))};
g.h.Rx=function(a,b){if(1==this.o){e8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lb.id});var c=a8(this);c.audioTrackId=b.Lb.id;c8(this,c)}else b8(this,g.Fa(this.Rx,a,b))};
g.h.aH=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Fa(this.aH,a,b))};
g.h.ZG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Fa(this.ZG,a,b))};
g.h.dA=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.dA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}$7.fa.dispose.call(this)};
g.h.X=function(){NEa(this);this.C=null;this.D.clear();Z7(this,null);$7.fa.X.call(this)};
g.h.Sx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.BC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.SU=function(a,b){this.V(a,b)};
g.h.rS=function(a){if(!a)this.Bn(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.h.Bn=function(a){j7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),OEa(this),this.V("remotePlayerChange")};
g.h.qS=function(a){a?(OEa(this),this.V("remotePlayerChange")):this.Bn(null)};
g.h.DS=function(){var a=KEa();a&&Z7(this,a)};
g.h.jc=function(a){j7("CP",a)};g.C(g8,g.UF);g.h=g8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=k||0;this.ib.state=3;V7(this.ib,m);this.C="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Jg(l));this.o.connect({method:"setPlaylist",
params:g.Jg(l)},a,jDa())}else h8("Connecting without params"),this.o.connect({},a,jDa());QEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),i8(this,3));g8.fa.dispose.call(this)};
g.h.X=function(){j8(this);l8(this);k8(this);g.kE(this.J);this.J=window.NaN;g.kE(this.K);this.K=window.NaN;this.B=null;g.EF(this.Y);this.Y.length=0;this.o.dispose();g8.fa.X.call(this);this.C=this.G=this.A=this.ib=this.o=null};
g.h.BL=function(){this.F(2)};
g.h.vS=function(){h8("Channel opened");this.O&&(this.O=!1,k8(this),this.N=g.iE((0,g.B)(function(){h8("Timing out waiting for a screen.");this.F(1)},this),15E3));
nDa($Da(this.o),this.ca)};
g.h.sS=function(){h8("Channel closed");(0,window.isNaN)(this.D)?w6(!0):w6();this.dispose()};
g.h.tS=function(a){w6();(0,window.isNaN)(this.H())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,h8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),i8(this,2))};
g.h.uS=function(a){a.params?h8("Received: action="+a.action+", params="+g.Jg(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.ix(a.params.devices);this.A=(0,g.I)(a,function(a){return new k6(a)});
a=!!g.Ka(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
TEa(this,a);break;case "loungeScreenDisconnected":g.Va(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
TEa(this,!1);break;case "remoteConnected":var b=new k6(g.ix(a.params.device));g.Ka(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new k6(g.ix(a.params.device));g.Va(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":VEa(this,a);break;case "nowPlaying":XEa(this,a);break;case "onStateChange":WEa(this,a);break;case "onAdStateChange":YEa(this,a);break;case "onVolumeChanged":ZEa(this,a);break;case "onSubtitlesTrackChanged":UEa(this,a);break;case "nowAutoplaying":$Ea(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":aFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.h.XW=function(){if(this.B){var a=this.B;this.B=null;this.ib.videoId!=a&&m8(this,"getNowPlaying")}};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.be;g8.prototype.ka=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?e7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
g8.prototype.getProxyState=g8.prototype.ka;g8.prototype.F=function(a){h8("Disconnecting with "+a);j8(this);this.V("beforeDisconnect",a);1==a&&w6();aEa(this.o,a);this.dispose()};
g8.prototype.disconnect=g8.prototype.F;g8.prototype.ia=function(){var a=this.ib;this.B&&(a=this.ib.clone(),X7(a,this.B,a.index));return Y7(a)};
g8.prototype.getPlayerContextData=g8.prototype.ia;
g8.prototype.pa=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.B=b.videoId,g.kE(this.J),this.J=g.iE((0,g.B)(this.XW,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.o==b.o&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&W7(this.ib)==W7(b)&&g.Jg(this.ib.A)==g.Jg(b.A)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
g8.prototype.setPlayerContextData=g8.prototype.pa;g8.prototype.aa=function(){var a=this.o.F.id,b=g.Ka(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
g8.prototype.getOtherConnectedRemoteId=g8.prototype.aa;g8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
g8.prototype.getReconnectTimeout=g8.prototype.H;g8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
g8.prototype.getAutoplayMode=g8.prototype.ba;g8.prototype.ga=function(){return this.G||""};
g8.prototype.getAutoplayVideoId=g8.prototype.ga;g8.prototype.xa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.nu(a.o);a.start()}};
g8.prototype.reconnect=g8.prototype.xa;g8.prototype.ma=function(a,b){m8(this,a,b);SEa(this)};
g8.prototype.sendMessage=g8.prototype.ma;g.C(n8,n7);g.h=n8.prototype;g.h.Ce=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Ir=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;n8.fa.X.call(this)};
g.h.rY=function(){this.V("screenChange")};
g.h.sU=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.sY;w7.prototype.$_gsppc=w7.prototype.eH;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Ir;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Ce;w7.prototype.$_gos=w7.prototype.dH;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.be;var o8=null,p8=null,E8=null,t8=[];g.r(F8,g.M);g.h=F8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.B.stop();this.C.stop();this.K.stop();this.N();this.o.unsubscribe("proxyStateChange",this.FE,this);this.o.unsubscribe("remotePlayerChange",this.En,this);this.o.unsubscribe("remoteQueueChange",this.Hq,this);this.o.unsubscribe("autoplayUpNext",this.bE,this);this.o.unsubscribe("previousNextChange",this.CE,this);this.o.unsubscribe("nowAutoplaying",this.tE,this);this.o.unsubscribe("autoplayDismissed",this.aE,this);this.o=this.G=null};
g.h.YC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(I8(this)){if(!a8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Em(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Rx(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();K8(this,0==c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Rx(this.T.getVideoData(1).videoId,c)}};
g.h.pS=function(a){this.K.wL(a)};
g.h.SX=function(a){this.YC("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.pG=function(){var a=this.T.Fc("captions","track");g.Zb(a)||J8(this,a)};
g.h.qE=function(a){if(I8(this)){this.o.unsubscribe("remotePlayerChange",this.En,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.En,this)}};
g.h.KT=function(){g.Zb(this.D)||mFa(this,this.D);this.F=!1};
g.h.FE=function(a,b){this.C.stop();2==b&&this.mG()};
g.h.En=function(){if(I8(this)){this.B.stop();var a=a8(this.o);switch(a.o){case 1081:case 1:H8(this,new g.VP(8));this.lG();break;case 1085:case 3:H8(this,new g.VP(9));break;case 1083:case 0:H8(this,new g.VP(2));this.J.stop();G8(this,this.T.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.VP(4));break;case 2:H8(this,new g.VP(4));G8(this,W7(a));break;case -1:H8(this,new g.VP(64));break;case -1E3:H8(this,new g.VP(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=
a8(this.o).A;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,mFa(this,a));a=a8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.LG()}else lFa(this)};
g.h.CE=function(){this.T.V("mdxpreviousnextchange")};
g.h.Hq=function(){I8(this)||lFa(this)};
g.h.BK=function(){this.o.dA()};
g.h.bE=function(a){a&&(a=g.zE("/watch_queue_ajax",{method:"GET",cd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.XV,this)}))&&(this.N=(0,g.B)(a.abort,a))};
g.h.XV=function(a,b){var c=new g.IO(g.Y(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.tE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.aE=function(){this.T.V("mdxautoplaycanceled")};
g.h.tQ=function(a,b){-1==a8(this.o).o?K8(this,a):b&&this.o.bH(a)};
g.h.LG=function(){if(I8(this)){var a=a8(this.o);this.A.Ga(this.O);a.muted?this.T.mute():this.T.wg();this.T.setVolume(a.volume);this.O=this.A.R(this.T,"onVolumeChange",this.qE)}};
g.h.lG=function(){this.B.stop();if(!this.o.la()){var a=a8(this.o);a.rb()&&H8(this,new g.VP(8));G8(this,W7(a));this.B.start()}};
g.h.mG=function(){this.C.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.C.start()};g.r(L8,g.W);L8.prototype.D=function(a){oFa(this,a.state)};g.r(M8,g.CY);M8.prototype.K=function(){var a=this.T.Fc("remote","receivers");a&&1<a.length&&!this.T.Fc("remote","quickCast")?(this.H=g.jb(a,this.D,this),g.DY(this,(0,g.I)(a,this.D)),a=this.T.Fc("remote","currentReceiver"),this.Jf(this.D(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.D=function(a){return a.key};
M8.prototype.If=function(a){return"cast-selector-receiver"==a?"Reparto...":this.H[a].name};
M8.prototype.Ed=function(a){g.CY.prototype.Ed.call(this,a);this.T.Vd("remote","currentReceiver",this.H[a]);this.C.Pb()};g.r(N8,g.GU);g.h=N8.prototype;g.h.create=function(){fFa(g.LM(g.Y(this.o)));this.F.push(g.fG("yt-remote-before-disconnect",this.lS,this));this.F.push(g.fG("yt-remote-connection-change",this.cV,this));this.F.push(g.fG("yt-remote-receiver-availability-change",this.DE,this));this.F.push(g.fG("yt-remote-auto-connect",this.aV,this));this.F.push(g.fG("yt-remote-receiver-resumed",this.ZU,this));this.DE()};
g.h.load=function(){this.o.Dv();g.GU.prototype.load.call(this);this.D=new F8(this,this.o,this.A);var a=(a=kFa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));nFa(this,this.G,this.G);g.N_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.mf(this.D,this.A);this.A=this.D=null;g.GU.prototype.unload.call(this);g.N_(this.o.app,5)};
g.h.X=function(){g.gG(this.F);g.GU.prototype.X.call(this)};
g.h.nn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.YC.apply(this.D,[a].concat(g.oa(c)))};
g.h.rL=function(){return this.loaded?this.D.suggestion:null};
g.h.ng=function(){return this.A?a8(this.A).ng:!1};
g.h.hasNext=function(){return this.A?a8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.hQ=function(){var a=a8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.nd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+U7(a):a.C,isPeggedToLive:1>=(a.F?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+U7(a):a.B,seekableStart:0<a.D?a.D+U7(a):a.D}};
g.h.iQ=function(){this.A&&this.A.ZG()};
g.h.jQ=function(){this.A&&this.A.aH()};
g.h.lS=function(a){1==a&&(this.K=this.A?a8(this.A):null)};
g.h.cV=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.lf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.CC(a.videoId,W7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.DE=function(){this.H=[this.B].concat(hFa());var a=z8()||this.B;O8(this,a);this.o.ya("onMdxReceiversChange")};
g.h.aV=function(){var a=z8();O8(this,a)};
g.h.ZU=function(){this.C=z8()};
g.h.gQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():O8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&Q7(),!0):!1}};
g.h.kQ=function(){e8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Nc=function(){return!1};g.CX.remote=N8;})(_yt_player);
